package health

type Allergy struct {
	Name string
}

// Source: https://en.wikipedia.org/wiki/List_of_allergens

var Allergies = []*Allergy{
	&Allergy{Name: "Balsam of Peru"},
	&Allergy{Name: "Buckwheat"},
	&Allergy{Name: "Celery"},
	&Allergy{Name: "Egg"},
	&Allergy{Name: "Fish"},
	&Allergy{Name: "Fruit"},
	&Allergy{Name: "Garlic"},
	&Allergy{Name: "Oats"},
	&Allergy{Name: "Maize"},
	&Allergy{Name: "Milk"},
	&Allergy{Name: "Mustard"},
	&Allergy{Name: "Peanut"},
	&Allergy{Name: "Poultry Meat"},
	&Allergy{Name: "Red Meat"},
	&Allergy{Name: "Rice"},
	&Allergy{Name: "Sesame"},
	&Allergy{Name: "Shellfish"},
	&Allergy{Name: "Soy"},
	&Allergy{Name: "Sulfites"},
	&Allergy{Name: "Tartrazine"},
	&Allergy{Name: "Tree nut"},
	&Allergy{Name: "Wheat"},
	&Allergy{Name: "Tetracycline"},
	&Allergy{Name: "Dilantin"},
	&Allergy{Name: "Tegretol (carbamazepine)"},
	&Allergy{Name: "Penicillin"},
	&Allergy{Name: "Cephalosporins"},
	&Allergy{Name: "Sulfonamides"},
	&Allergy{Name: "Non-steroidal anti-inflammatories"},
	&Allergy{Name: "Cromolyn odium"},
	&Allergy{Name: "Nedocromil odium"},
	&Allergy{Name: "Intravenous contrast dye"},
	&Allergy{Name: "Local anesthetics"},
	&Allergy{Name: "Pollen"},
	&Allergy{Name: "Cat"},
	&Allergy{Name: "Dog"},
	&Allergy{Name: "Insect sting"},
	&Allergy{Name: "Mold"},
	&Allergy{Name: "Perfume"},
	&Allergy{Name: "Cosmetics"},
	&Allergy{Name: "Semen"},
	&Allergy{Name: "Latex"},
	&Allergy{Name: "Water"},
	&Allergy{Name: "Cold stimuli"},
	&Allergy{Name: "House dust mite"},
	&Allergy{Name: "Nickel (nickel sulfate hexahydrate)"},
	&Allergy{Name: "Gold (gold sodium thiosulfate)"},
	&Allergy{Name: "Chromium"},
	&Allergy{Name: "Cobalt chloride"},
	&Allergy{Name: "Formaldehyde"},
	&Allergy{Name: "Photographic developers"},
	&Allergy{Name: "Fungicide"},
	&Allergy{Name: "Dimethylaminopropylamine (DMAPA)"},
	&Allergy{Name: "Paraphenylenediamine (PPD)"},
	&Allergy{Name: "Glyceryl monothioglycolate"},
	&Allergy{Name: "Toluenesulfonamide formaldehyde (Toluidine)"},
}
