package health

// Illness is a structure to represent either a disease (something that must be cured) or perm/temp condition (something that must be managed).
type Illness struct {
	Name string
}

// Illnesses is a A to Z list of common disease, illnesses and conditions according to the Scotland's national health information service (NHS) via https://www.nhsinform.scot/illnesses-and-conditions/a-to-z.
var Illnesses = []*Illness{
	&Illness{Name: "Abdominal aortic aneurysm"},
	&Illness{Name: "Acne"},
	&Illness{Name: "Acute cholecystitis"},
	&Illness{Name: "Acute lymphoblastic leukaemia"},
	&Illness{Name: "Acute myeloid leukaemia"},
	&Illness{Name: "Acute pancreatitis"},
	&Illness{Name: "Addison's disease"},
	&Illness{Name: "Alcohol-related liver disease"},
	&Illness{Name: "Allergic rhinitis"},
	&Illness{Name: "Allergies"},
	&Illness{Name: "Alzheimer's disease"},
	&Illness{Name: "Anal cancer"},
	&Illness{Name: "Anaphylaxis"},
	&Illness{Name: "Angioedema"},
	&Illness{Name: "Ankylosing spondylitis"},
	&Illness{Name: "Anorexia nervosa"},
	&Illness{Name: "Anxiety"},
	&Illness{Name: "Appendicitis"},
	&Illness{Name: "Arthritis"},
	&Illness{Name: "Asbestosis"},
	&Illness{Name: "Asthma"},
	&Illness{Name: "Atopic eczema"},
	&Illness{Name: "Attention deficit hyperactivity disorder (ADHD)"},
	&Illness{Name: "Autistic spectrum disorder (ASD)"},
	&Illness{Name: "Bacterial vaginosis"},
	&Illness{Name: "Benign prostate enlargement"},
	&Illness{Name: "Bile duct cancer (cholangiocarcinoma)"},
	&Illness{Name: "Binge eating"},
	&Illness{Name: "Bipolar disorder"},
	&Illness{Name: "Bladder cancer"},
	&Illness{Name: "Blood poisoning (sepsis)"},
	&Illness{Name: "Bone cancer"},
	&Illness{Name: "Bone cancer: Teenagers and young adults"},
	&Illness{Name: "Bowel cancer"},
	&Illness{Name: "Bowel incontinence"},
	&Illness{Name: "Bowel polyps"},
	&Illness{Name: "Brain stem death"},
	&Illness{Name: "Brain tumours"},
	&Illness{Name: "Brain tumours: Children"},
	&Illness{Name: "Brain tumours: Teenagers and young adults"},
	&Illness{Name: "Breast cancer (female)"},
	&Illness{Name: "Breast cancer (male)"},
	&Illness{Name: "Bronchiectasis"},
	&Illness{Name: "Bronchitis"},
	&Illness{Name: "Bulimia"},
	&Illness{Name: "Bunion"},
	&Illness{Name: "Carcinoid syndrome and carcinoid tumours"},
	&Illness{Name: "Catarrh"},
	&Illness{Name: "Cellulitis"},
	&Illness{Name: "Cervical cancer"},
	&Illness{Name: "Chest infection"},
	&Illness{Name: "Chest pain"},
	&Illness{Name: "Chickenpox"},
	&Illness{Name: "Chilblains"},
	&Illness{Name: "Chlamydia"},
	&Illness{Name: "Chronic fatigue syndrome"},
	&Illness{Name: "Chronic kidney disease"},
	&Illness{Name: "Chronic lymphocytic leukaemia"},
	&Illness{Name: "Chronic myeloid leukaemia"},
	&Illness{Name: "Chronic obstructive pulmonary disease"},
	&Illness{Name: "Chronic pancreatitis"},
	&Illness{Name: "Cirrhosis"},
	&Illness{Name: "Clostridium difficile"},
	&Illness{Name: "Coeliac disease"},
	&Illness{Name: "Cold sore"},
	&Illness{Name: "Coma"},
	&Illness{Name: "Common cold"},
	&Illness{Name: "Common heart conditions"},
	&Illness{Name: "Congenital heart disease"},
	&Illness{Name: "Conjunctivitis"},
	&Illness{Name: "Constipation"},
	&Illness{Name: "Coronavirus (COVID-19)"},
	&Illness{Name: "Cough"},
	&Illness{Name: "Crohn's disease"},
	&Illness{Name: "Croup"},
	&Illness{Name: "Cystic fibrosis"},
	&Illness{Name: "Cystitis"},
	&Illness{Name: "Deafblindness"},
	&Illness{Name: "Deep vein thrombosis"},
	&Illness{Name: "Dehydration"},
	&Illness{Name: "Dementia"},
	&Illness{Name: "Dementia with Lewy bodies"},
	&Illness{Name: "Dental abscess"},
	&Illness{Name: "Depression"},
	&Illness{Name: "Dermatitis herpetiformis"},
	&Illness{Name: "Diabetes"},
	&Illness{Name: "Diarrhoea"},
	&Illness{Name: "Discoid eczema"},
	&Illness{Name: "Diverticular disease and diverticulitis"},
	&Illness{Name: "Dizziness (Lightheadedness)"},
	&Illness{Name: "Down's syndrome"},
	&Illness{Name: "Dry mouth"},
	&Illness{Name: "Dysphagia (swallowing problems)"},
	&Illness{Name: "Dystonia"},
	&Illness{Name: "Earache"},
	&Illness{Name: "Earwax build-up"},
	&Illness{Name: "Ebola virus disease"},
	&Illness{Name: "Ectopic pregnancy"},
	&Illness{Name: "Endometriosis"},
	&Illness{Name: "Epilepsy"},
	&Illness{Name: "Erectile dysfunction (impotence)"},
	&Illness{Name: "Escherichia coli (E. coli) O157"},
	&Illness{Name: "Ewing sarcoma"},
	&Illness{Name: "Ewing sarcoma: Children"},
	&Illness{Name: "Eye cancer"},
	&Illness{Name: "Febrile seizures"},
	&Illness{Name: "Fever in adults"},
	&Illness{Name: "Fever in children"},
	&Illness{Name: "Fibroids"},
	&Illness{Name: "Fibromyalgia"},
	&Illness{Name: "Flatulence"},
	&Illness{Name: "Flu"},
	&Illness{Name: "Foetal alcohol syndrome"},
	&Illness{Name: "Food poisoning"},
	&Illness{Name: "Fungal nail infection"},
	&Illness{Name: "Gallbladder cancer"},
	&Illness{Name: "Gallstones"},
	&Illness{Name: "Ganglion cyst"},
	&Illness{Name: "Gastroenteritis"},
	&Illness{Name: "Gastro-oesophageal reflux disease (GORD)"},
	&Illness{Name: "Genital herpes"},
	&Illness{Name: "Genital warts"},
	&Illness{Name: "Germ cell tumours"},
	&Illness{Name: "Glandular fever"},
	&Illness{Name: "Gonorrhoea"},
	&Illness{Name: "Gout"},
	&Illness{Name: "Gum disease"},
	&Illness{Name: "Haemorrhoids (piles)"},
	&Illness{Name: "Hairy cell leukaemia"},
	&Illness{Name: "Hand, foot and mouth disease"},
	&Illness{Name: "Hay fever"},
	&Illness{Name: "Head and neck cancer"},
	&Illness{Name: "Head lice and nits"},
	&Illness{Name: "Headaches"},
	&Illness{Name: "Hearing loss"},
	&Illness{Name: "Heart failure"},
	&Illness{Name: "Hepatitis A"},
	&Illness{Name: "Hepatitis B"},
	&Illness{Name: "Hepatitis C"},
	&Illness{Name: "Hiatus hernia"},
	&Illness{Name: "High cholesterol"},
	&Illness{Name: "HIV"},
	&Illness{Name: "Hodgkin lymphoma"},
	&Illness{Name: "Hodgkin lymphoma: Children"},
	&Illness{Name: "Hodgkin lymphoma: Teenagers and young adults"},
	&Illness{Name: "Huntington's disease"},
	&Illness{Name: "Hyperglycaemia (high blood sugar)"},
	&Illness{Name: "Hyperhidrosis"},
	&Illness{Name: "Hypoglycaemia (low blood sugar)"},
	&Illness{Name: "Idiopathic pulmonary fibrosis"},
	&Illness{Name: "Impetigo"},
	&Illness{Name: "Indigestion"},
	&Illness{Name: "Ingrown toenail"},
	&Illness{Name: "Inherited heart conditions"},
	&Illness{Name: "Insomnia"},
	&Illness{Name: "Iron deficiency anaemia"},
	&Illness{Name: "Irritable bowel syndrome (IBS)"},
	&Illness{Name: "Irritable hip"},
	&Illness{Name: "Itching"},
	&Illness{Name: "Itchy bottom"},
	&Illness{Name: "Kaposi's sarcoma"},
	&Illness{Name: "Kidney cancer"},
	&Illness{Name: "Kidney infection"},
	&Illness{Name: "Kidney stones"},
	&Illness{Name: "Labyrinthitis"},
	&Illness{Name: "Lactose intolerance"},
	&Illness{Name: "Langerhans cell histiocytosis"},
	&Illness{Name: "Laryngeal (larynx) cancer"},
	&Illness{Name: "Laryngitis"},
	&Illness{Name: "Leg cramps"},
	&Illness{Name: "Lichen planus"},
	&Illness{Name: "Liver cancer"},
	&Illness{Name: "Liver disease"},
	&Illness{Name: "Liver tumours"},
	&Illness{Name: "Loss of libido"},
	&Illness{Name: "Lung cancer"},
	&Illness{Name: "Lupus"},
	&Illness{Name: "Lyme disease"},
	&Illness{Name: "Lymphoedema"},
	&Illness{Name: "Lymphogranuloma venereum (LGV)"},
	&Illness{Name: "Malaria"},
	&Illness{Name: "Malignant brain tumour (cancerous)"},
	&Illness{Name: "Malnutrition"},
	&Illness{Name: "Measles"},
	&Illness{Name: "Meningitis"},
	&Illness{Name: "Menopause"},
	&Illness{Name: "Mesothelioma"},
	&Illness{Name: "Middle ear infection (otitis media)"},
	&Illness{Name: "Migraine"},
	&Illness{Name: "Miscarriage"},
	&Illness{Name: "Motor neurone disease (MND)"},
	&Illness{Name: "Mouth cancer"},
	&Illness{Name: "Mouth ulcer"},
	&Illness{Name: "Multiple myeloma"},
	&Illness{Name: "Multiple sclerosis (MS)"},
	&Illness{Name: "Mumps"},
	&Illness{Name: "Meniere's disease"},
	&Illness{Name: "Nasal and sinus cancer"},
	&Illness{Name: "Nasopharyngeal cancer"},
	&Illness{Name: "Neuroblastoma"},
	&Illness{Name: "Neuroblastoma: Children"},
	&Illness{Name: "Neuroendocrine tumours"},
	&Illness{Name: "Non-alcoholic fatty liver disease (NAFLD)"},
	&Illness{Name: "Non-Hodgkin lymphoma"},
	&Illness{Name: "Non-Hodgkin lymphoma: Children"},
	&Illness{Name: "Norovirus"},
	&Illness{Name: "Nosebleed"},
	&Illness{Name: "Obesity"},
	&Illness{Name: "Obsessive compulsive disorder (OCD)"},
	&Illness{Name: "Obstructive sleep apnoea"},
	&Illness{Name: "Oesophageal cancer"},
	&Illness{Name: "Oral thrush in adults"},
	&Illness{Name: "Osteoarthritis"},
	&Illness{Name: "Osteoporosis"},
	&Illness{Name: "Osteosarcoma"},
	&Illness{Name: "Otitis externa"},
	&Illness{Name: "Ovarian cancer"},
	&Illness{Name: "Ovarian cancer: Teenagers and young adults"},
	&Illness{Name: "Ovarian cyst"},
	&Illness{Name: "Overactive thyroid"},
	&Illness{Name: "Paget's disease of the nipple"},
	&Illness{Name: "Pancreatic cancer"},
	&Illness{Name: "Panic disorder"},
	&Illness{Name: "Parkinson's disease"},
	&Illness{Name: "Pelvic inflammatory disease"},
	&Illness{Name: "Pelvic organ prolapse"},
	&Illness{Name: "Penile cancer"},
	&Illness{Name: "Peripheral neuropathy"},
	&Illness{Name: "Personality disorder"},
	&Illness{Name: "Pleurisy"},
	&Illness{Name: "Pneumonia"},
	&Illness{Name: "Polymyalgia rheumatica"},
	&Illness{Name: "Post-traumatic stress disorder (PTSD)"},
	&Illness{Name: "Postnatal depression"},
	&Illness{Name: "Pregnancy and baby"},
	&Illness{Name: "Pressure ulcers"},
	&Illness{Name: "Prostate cancer"},
	&Illness{Name: "Psoriasis"},
	&Illness{Name: "Psoriatic arthritis"},
	&Illness{Name: "Psychosis"},
	&Illness{Name: "Pubic lice"},
	&Illness{Name: "Rare tumours"},
	&Illness{Name: "Raynaud's phenomenon"},
	&Illness{Name: "Reactive arthritis"},
	&Illness{Name: "Restless legs syndrome"},
	&Illness{Name: "Retinoblastoma"},
	&Illness{Name: "Retinoblastoma: Children"},
	&Illness{Name: "Rhabdomyosarcoma"},
	&Illness{Name: "Rheumatoid arthritis"},
	&Illness{Name: "Ringworm and other fungal infections"},
	&Illness{Name: "Rosacea"},
	&Illness{Name: "Scabies"},
	&Illness{Name: "Scarlet fever"},
	&Illness{Name: "Schizophrenia"},
	&Illness{Name: "Scoliosis"},
	&Illness{Name: "Septic shock"},
	&Illness{Name: "Shingles"},
	&Illness{Name: "Shortness of breath"},
	&Illness{Name: "Sickle cell disease"},
	&Illness{Name: "Sinusitis"},
	&Illness{Name: "Sjogren's syndrome"},
	&Illness{Name: "Skin cancer (melanoma)"},
	&Illness{Name: "Skin cancer (non-melanoma)"},
	&Illness{Name: "Slapped cheek syndrome"},
	&Illness{Name: "Soft tissue sarcomas"},
	&Illness{Name: "Soft tissue sarcomas: Teenagers and young adults"},
	&Illness{Name: "Sore throat"},
	&Illness{Name: "Spleen problems and spleen removal"},
	&Illness{Name: "Stillbirth"},
	&Illness{Name: "Stomach ache and abdominal pain"},
	&Illness{Name: "Stomach cancer"},
	&Illness{Name: "Stomach ulcer"},
	&Illness{Name: "Stress, anxiety and low mood"},
	&Illness{Name: "Stroke"},
	&Illness{Name: "Sudden infant death syndrome (SIDS)"},
	&Illness{Name: "Suicide"},
	&Illness{Name: "Sunburn"},
	&Illness{Name: "Swollen glands"},
	&Illness{Name: "Syphilis"},
	&Illness{Name: "Testicular cancer"},
	&Illness{Name: "Testicular cancer: Teenagers and young adults"},
	&Illness{Name: "Testicular lumps and swellings"},
	&Illness{Name: "Thirst"},
	&Illness{Name: "Threadworms"},
	&Illness{Name: "Thrush"},
	&Illness{Name: "Thrush in men"},
	&Illness{Name: "Thyroid cancer"},
	&Illness{Name: "Thyroid cancer: Teenagers and young adults"},
	&Illness{Name: "Tinnitus"},
	&Illness{Name: "Tonsillitis"},
	&Illness{Name: "Tooth decay"},
	&Illness{Name: "Toothache"},
	&Illness{Name: "Transient ischaemic attack (TIA)"},
	&Illness{Name: "Trigeminal neuralgia"},
	&Illness{Name: "Tuberculosis (TB)"},
	&Illness{Name: "Type 1 diabetes"},
	&Illness{Name: "Type 2 diabetes"},
	&Illness{Name: "Trichomonas infection"},
	&Illness{Name: "Ulcerative colitis"},
	&Illness{Name: "Underactive thyroid"},
	&Illness{Name: "Urinary incontinence"},
	&Illness{Name: "Urinary tract infection (UTI)"},
	&Illness{Name: "Urinary tract infection (UTI) in children"},
	&Illness{Name: "Urticaria (hives)"},
	&Illness{Name: "Vaginal cancer"},
	&Illness{Name: "Vaginal thrush"},
	&Illness{Name: "Varicose eczema"},
	&Illness{Name: "Venous leg ulcer"},
	&Illness{Name: "Vertigo"},
	&Illness{Name: "Vitamin B12 or folate deficiency anaemia"},
	&Illness{Name: "Vomiting in adults"},
	&Illness{Name: "Vulval cancer"},
	&Illness{Name: "Warts and verrucas"},
	&Illness{Name: "Whooping cough"},
	&Illness{Name: "Wilms’ tumour"},
	&Illness{Name: "Womb (uterus) cancer"},
	&Illness{Name: "Yellow fever"},
}
